#!/bin/bash
#
# script to compile yap for Android.

PROJECT=~/github/YAPDroid

APP_SRC=$PROJECT/app
YAP_SRC=$APP_SRC

cd ${APP_SRC}/src

# you need yap and gmp, please:
if [ ! -e yap ]
then
    git clone https://github.com/vscosta/yap-6.3.git yap
fi
if [ ! -e yap ]
then
    git clonehttps://github.com/Rupan/gmp.git
fi


#clean up
rm -rf .externalNativeBuild build generated src/main/java/pt/up/yap/lib

# ensure these two directories exist
mkdir -p externalNativeBuild/swig
mkdir -p src/main/java/pt/up/yap/lib

# call swig to generate the java->C++ interface
swig -Wall  -c++  -I../../H -Isrc/yap/H/generated \
      -Isrc/yap/include -Isrc/yap/os -Isrc/yap/OPTYap \
      -Isrc/yap/utf8proc -Isrc/yap/CXX -java  \
      -package pt.up.yap.lib \
      -outdir src/main/java/pt/up/yap/lib \
      -o $APP_SRC/externalNativeBuild/swig/yapj.cpp \
      -addextern \
      src/yap/packages/swig/yap.i

#create assets by hand
mkdir -p  assets/share/Yap/pl
mkdir -p  assets/share/Yap/os
cp -a src/yap/library/*.pl src/yap/library/*.yap assets/share/Yap
cp -a src/yap/pl/*.yap assets/share/Yap/pl
cp -a src/yap/os/*.yap assets/share/Yap/os

#in WIN32 install  gcc/ clang or use /EP /P
for i in  myddas \
  myddas_assert_predicates \
  myddas_top_level \
  myddas_errors \
  myddas_prolog2sql \
  myddas_mysql \
  myddas_util_predicates \
  myddas_prolog2sql_optimizer ; do
    gcc -x c -E -P -w   -o assets/share/Yap/$i.yap src/yap/packages/myddas/pl/$i.ypp;\
	done
    gcc -x c -E -P -w -DMYDDAS_SQLITE3  -o assets/share/Yap/myddas_sqlite3.yap src/yap/packages/myddas/plmyddas_driver.ypp


cd ..

chmod +x ./gradlew

# ./gradlew tasks

# this will fail unless the emulator is active, but will generate the APK
./gradlew installDebug
