#!/bin/bash
#
# script to compile yap for Android.

# This is a number of steps to prepare a version of YAP for
# compilation can run it as a script, or build one by one. Run it in
# WIN32 by running step by step.

# I assume we have a gmp directory (from  https://github.com/Rupan/gmp )
cd src/
# git clone  https://github.com/Rupan/gmp    
#if you have one, say two directories above:
ln -sf ../../../gmp .

#yap
# git clone  https://github.com/vscosta/yap-6.3 yap
#if you have one, say two directories above:
ln -sf ../../../yap-6.3 yap

# back to where we started
cd ..

# you now the android app, yap and gmp.


#
# cleanup existing files.
#
rm -rf externalNativeBuild build generated src/main/java/pt/up/yap/lib


#intermediate C++ files go here
mkdir -p externalNativeBuild/swig
# JAVA->YAP interface goes here.
mkdir -p src/main/java/pt/up/yap/lib

#run swig to set yp the interface
swig -Wall  -c++  -I../../H -Isrc/yap/H/generated \
      -Isrc/yap/include -Isrc/yap/os -Isrc/yap/OPTYap \
      -Isrc/yap/utf8proc -Isrc/yap/CXX -java  \
      -package pt.up.yap.lib \
      -outdir src/main/java/pt/up/yap/lib \
      -o externalNativeBuild/swig/yapj.cpp \
      -addextern \
      src/yap/packages/swig/yap.i

# copy files
mkdir -p  assets/share/Yap/pl
mkdir -p  assets/share/Yap/os
cp -a src/yap/library/*.pl src/yap/library/*.yap assets/share/Yap
cp -a src/yap/pl/*.yap assets/share/Yap/pl
cp -a src/yap/os/*.yap assets/share/Yap/os

#in WIN32 install  gcc/ clang or use /EP /P
for i in  myddas \
  myddas_assert_predicates \
  myddas_top_level \
  myddas_errors \
  myddas_prolog2sql \
  myddas_mysql \
  myddas_util_predicates \
  myddas_prolog2sql_optimizer ; do
    gcc -x c -E -P -w   -o assets/share/Yap/$i.yap src/yap/packages/myddas/pl/$i.ypp;\
	done
  gcc -x c -E -P -w -DMYDDAS_SQLITE3=1  -o assets/share/Yap/myddas_sqlite3.yap src/yap/packages/myddas/pl/myddas_driver.ypp;\

  gcc -x c -E -P -w -DMYDDAS_ODBC=1  -o assets/share/Yap/myddas_odbc.yap src/yap/packages/myddas/pl/myddas_driver.ypp;\

  gcc -x c -E -P -w -DMYDDAS_SQLITE3=1  -o assets/share/Yap/myddas_sqlite3.yap src/yap/packages/myddas/pl/myddas_driver.ypp;\


cd ..

# gradlew is our make
chmod +x ./gradlew

./gradlew tasks

./gradlew installDebug

# at the end this will fail if you don't have an emulator running.
